### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by epaminond** [Orange-OpenSource/angular-swagger-ui#2]
Hi! Are there any plans to write documentation with some basic examples of usage?

**Comment by maales** [comment]
Hi !
This tool is based on Swagger, you can find more informations here: http://swagger.io
Here is an editor to create your Swagger documentation: http://editor.swagger.io
Here are Swagger specifications: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md
