### ISSUE TITLE
How to you pass authorization tokens

### ISSUE THREAD

**Issue by mittalsumeet** [Orange-OpenSource/angular-swagger-ui#20]
Hi

I have auth token that need to be passed as header "X-Auth-Token" for each request. How do I pass that in the swagger definition json file?

**Comment by kreck** [comment]
you should use 
`$http.defaults.headers.common['X-AUTH-TOKEN'] = whateveryourtokenis`

Check out this link for the properties
https://docs.angularjs.org/api/ng/provider/$httpProvider

**Comment by mathieuales** [comment]
You can also write a module as described [here](https://github.com/Orange-OpenSource/angular-swagger-ui#writing-your-own-modules) to modify API explorer requests
