### ISSUE TITLE
Custom template?

### ISSUE THREAD

**Issue by andreaslarssen** [Orange-OpenSource/angular-swagger-ui#3]
It would be nice to be able to pass a optional template URL to the directive.
On another hand, I guess that's where most of the time saving are done using this lib, not having to style the response.

**Comment by mathieuales** [comment]
Hi !

What would you like to change in the template ? Can't you achieve UI customization using CSS ?
The aim of this lib is to render API documentation as swagger-ui does but without loading a huge amount of JS (more than 2MB) 
Anyway, i'll keep the idea in mind.

Regards

**Comment by andreaslarssen** [comment]
I agree, it's not what this lib is supposed to do.
