### ISSUE TITLE
0.2.7 Archive for Bower still has 0.2.6 version.

### ISSUE THREAD

**Issue by testn** [Orange-OpenSource/angular-swagger-ui#30]
Here is package.json content in https://github.com/Orange-OpenSource/angular-swagger-ui/releases/tag/0.2.7:

{
  "name": "angular-swagger-ui",
  "version": "**0.2.6**",
  "dependencies": {},
  "devDependencies": {
    "glob": "^4.3.5",
    "grunt": "^0.4.5",
    "grunt-concurrent": "^1.0.0",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-concat": "^0.5.0",
    "grunt-contrib-connect": "^0.9.0",
    "grunt-contrib-copy": "^0.7.0",
    "grunt-contrib-jshint": "^0.11.0",
    "grunt-contrib-less": "^1.0.0",
    "grunt-contrib-uglify": "^0.9.2",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-html2js": "^0.3.0",
    "grunt-newer": "^1.1.0",
    "jshint-stylish": "^1.0.0",
    "load-grunt-tasks": "^3.0.0",
    "matchdep": "^0.3.0",
    "time-grunt": "^1.0.0"
  },
  "engines": {
    "node": ">=0.10.0"
  }
}

**Comment by mathieuales** [comment]
If you have a look at `package.json` in the repository the version is correct.
As this file is now ignored by bower you should delete folder `bower_components/angular-swagger-ui` and run `bower update` then everything should be ok
