### ISSUE TITLE
Bower install does not work

### ISSUE THREAD

**Issue by DavidPautet** [Orange-OpenSource/angular-swagger-ui#31]
Hi,

Thank you for this nice project (quite nice to integrate our Swagger doc within our angular app) !

Just to let you know: **there is still an issue with "bower install"** since the retrieved version is not the correct one (seems to be quite old). Your last commit seems to be associated to this issue but does not fix any thing for me...

In addition, do you accept pull request since I have prepared a small enhancement to transform model properties into links ?

Assuming we have the following model:
![image](https://cloud.githubusercontent.com/assets/6059057/11244949/9f0db41e-8e10-11e5-9172-c67922a7bc19.png)
In the "CustomerStub", "contacts" is an array of "Contact" object and now you can click to navigate directly towards this definition in the model (interesting when you have a large model).

the generated HTML looks like this:
- classes with a `<span>` and an `id` attribute:
  `<span id="customer:CustomerStub">customer:CustomerStub</span>`
- properties with `<a>` with `href` atttribute:
  `<a href="#/admin/doc/customer#customer:contact:Contacts">customer:contact:Contacts</a>`

This implies to simply pass to the swagger-ui directive a new parameter with route base (`#/admin/doc/customer` in my example) to be used within href (link within the same page - to avoid any interaction with ui.router).
`<div swagger-ui url="swaggerUrl" loading="isLoading" ref-link-base-url="stateUrl" api-explorer="false" permalinks="true" validator-url="false" trusted-sources="true" error-handler="swaggerErrorHandler">`

Please let me know if you are interested in reviewing this.
Thanks.

**Comment by mathieuales** [comment]
Hi !
I can't reproduce any issue with `bower` ... what is the error message ? If you still have an errror, you can try deleting previous version of `angular-swagger-ui` and run `bower cache clean`
And sure, I accept pull requests !

**Comment by DavidPautet** [comment]
Thanks, after a clean cache things are getting better. Problem solved.
