### ISSUE TITLE
The swagger1-to-swagger2-converter fails to create models with references

### ISSUE THREAD

**Issue by larandersson** [Orange-OpenSource/angular-swagger-ui#35]
If a swagger 1.X specification contains a model with objects that contain references to other objects in the model, the referenced objects are not handled properly. The problem is located in lines 184-190 of the script, where the _type_ property is being used instead of the _$ref_ one, so the code should probably be changed to be something like the one below, which works fine for me:

```
if (swagger1.models && swagger1.models[prop.$ref]) {
  prop.$ref = '#/definitions/' + prop.$ref;
  //delete prop.type; // Not quite sure what this line is for?
}
if (prop.items && swagger1.models && swagger1.models[prop.items.$ref]) {
  prop.items.$ref = '#/definitions/' + prop.items.$ref;
  //delete prop.items.type; // Not quite sure what this line is for?
}
```

Thanks.

Regards

Lars

**Comment by mathieuales** [comment]
You're right, it will be fixed in next release.
Thanks for your contribution
