### ISSUE TITLE
Modifying POST body has no effect

### ISSUE THREAD

**Issue by stiggg** [Orange-OpenSource/angular-swagger-ui#36]
It seems modifying the POST body after sending a request with "Try it out" has no effect. Old body string is sent regardless. Is the body cached somewhere? My angular-swagger-ui version is 0.2.6.

**Comment by mathieuales** [comment]
Hi !
There is no cache when using API explorer.
I just made a test [here](http://orange-opensource.github.io/angular-swagger-ui/) and everything seems ok (version is 0.2.6 too).
Could you please give more details on how you use the component ?

**Comment by stiggg** [comment]
My steps to reproduce it: I click on "model schema", which gets copied onto object which has type "body". I modify the copied JSON string a bit, click "try it out" and get a response. After that, I modify the JSON a bit more, and again click "try it out". This time however the same string that was sent the first time is POSTed.

I tried it with the test explorer you linked above and could not reproduce it there. I think I have to look more into it, to figure out what is going on. I set up the explorer with the instructions in README. What kind of information would you need about how I'm using it?

**Comment by MaciejDobrowolski** [comment]
+1
