### ISSUE TITLE
Authentication Support for Swagger 2.0

### ISSUE THREAD

**Issue by peterfust** [Orange-OpenSource/angular-swagger-ui#38]
Are there any intentions to support authentication based on Security information in a Swagger 2.0 description?

**Comment by mathieuales** [comment]
I'd like to but I don't have much time to do so for the moment ...
Feel free to implement it and share :-)

**Comment by mathieuales** [comment]
partially implemented in `0.3.5`
oauth is not implemented

**Comment by mathieuales** [comment]
done in release 0.5.4
