### ISSUE TITLE
Swagger UI Displays but I get an "ERROR" indicator

### ISSUE THREAD

**Issue by fluky** [Orange-OpenSource/angular-swagger-ui#43]
My UI displays and it is showing all of my routes.   Everything looks great except there is a big red ERROR indicator on the lower right.  When I click it I get:

`{"schemaValidationMessages":[{"level":"error","message":"Can't read from file /swagger.json"}]}`

Obviously if it couldn't read the json file it wouldn't be displaying my documentaion.

**Comment by mathieuales** [comment]
Hi !
This error is displayed by the swagger schema validator, it does not mean your swagger descriptor is not readable by `angular-swagger-ui`. The swagger validator is hosted at http://online.swagger.io/validator. You can disable schema validation by setting `validatorUrl="false"` on the directive if your URL is not public or put an absolute URL. I'll fix the issue for relative URLs in next release.

**Comment by fluky** [comment]
Thanks.

**Comment by ayushidalmia** [comment]
I am using local json files and hence come across this error.  My current parameters are as follows:

```
window.swaggerUi = new SwaggerUi({
        url: url,
        spec: spec,
        dom_id: "swagger-ui-container",
      ...
```

where url is set to url="" in a js function.

If I don't set the variable url, it does not show anything

Similarly, if I set         validatorUrl=null, it does not display the content. 

How to go about it?

**Comment by mathieuales** [comment]
Hi !
It looks like you're not using `angular-swagger-ui` 
To use this library please have a look at https://github.com/Orange-OpenSource/angular-swagger-ui#getting-started

**Comment by ayushidalmia** [comment]
What does angular swagger do?

**Comment by mg1986jp** [comment]
Good morning.
Because I am a Japanese human, it is difficult to interpret the document.

>This error is displayed by the swagger schema validator, it does not mean your swagger descriptor is not readable

Do not you have to worry about this error?
