### ISSUE TITLE
Basepath Problem

### ISSUE THREAD

**Issue by samypr100** [Orange-OpenSource/angular-swagger-ui#46]
This issue is about swagger spec and base path behavior.
Using this library if you set it to "/" (meaning root), it's appending a "/" to the end of the url resulting in `http(s)://host:port/apiRoute//...` it should be `http(s)://host:port/apiRoute/...`
Instead if it's not simply "/", and something like "/basepath/" it's correct to append a "/" on the end if it doesn't exist.
I don't have this issue with swagger-ui itself, hence I though I should bring it up.

**Comment by daniel-cotton** [comment]
Should be able to close now - addressed in #58

**Comment by anil2** [comment]
I see that the problem is addressed and solved, may I know when will it be available in release? I see that the packages downloaded via bower still have the old version. Thanks.
