### ISSUE TITLE
Failed to generate Swagger-UI: -1 

### ISSUE THREAD

**Issue by ddbaron** [Orange-OpenSource/angular-swagger-ui#48]
I've generated the following swagger 2.0 compliant json (and yaml). I receive the subject error when trying the demo app. 

[https://q-api.mybluemix.net/js/quarky.yaml](url)
[https://q-api.mybluemix.net/js/quarky.json](url)

Any suggestions?

**Comment by mathieuales** [comment]
It's working for me on the sample page : http://orange-opensource.github.io/angular-swagger-ui
Do you still have the issue ?

**Comment by mathieuales** [comment]
This error can occur if cross-domain is not activated on server hosting your swagger descriptor
Any news ?

**Comment by ddbaron** [comment]
It must have been an issue on my side... it's working now yet I confess I don't know what changed.
