### ISSUE TITLE
UI thread being blocked

### ISSUE THREAD

**Issue by maaso** [Orange-OpenSource/angular-swagger-ui#49]
Hi, 

I'm loading in swagger json that has been stored in a DB (so not loading from a URL, but passing in a JSON object); for larger Swagger JSON objects angular-swagger-ui needs a couple of seconds to parse all the data, during which the UI thread gets blocked, resulting in a poor user experience

Is anybody else seeing this behaviour, and if so, can this be remedies somehow (maybe by using web workers)?

**Comment by maaso** [comment]
Turns out it was the rendering of the template, not the parsing that was blocking the UI.

Fixed this by tweaking the template a bit (mainly by using ng-if to prevent lower levels from being rendered)

**Comment by mathieuales** [comment]
Hi !

Could you please share the changes you made on the template ?

**Comment by maaso** [comment]
Sure, it's very simple really.

I've created a pull request: #51 

Please note that I have not thoroughly tested this yet, so maybe it breaks something that I have not yet noticed.
