### ISSUE TITLE
Internationalization dir for rtl languages

### ISSUE THREAD

**Issue by yanzacheus** [Orange-OpenSource/angular-swagger-ui#53]
Hello,
I tried to implement arabic language, and as it's written from right to left (rtl), I wanted to add the dir attribute(="rtl") to the swagger-ui directive.
In fact, I switch the dir attribute value according to the language selected.
Almost works !
Elements are rendered from right to left except that:
1 - Resource Names (from tags) remain in the left part
2 - Vertical Lines remain to the right of the commands

These 2 points are the main ones, for the second , it's related to these css rules:
(sorry I looked directly at the css file generated, not in the less files)
.swagger-ui .endpoint .endpoint-actions li {
  border-right: 1px solid #ddd;
}
.swagger-ui .endpoint .endpoint-actions li:last-child {
  border-right: 0;
}

So if I want to make it work, I need to add:
[dir='rtl']
.swagger-ui .endpoint .endpoint-actions li {
  border-**left**: 1px solid #ddd;
}
.swagger-ui .endpoint .endpoint-actions li:last-child {
  border-**left**: 0;
}

or :)
[dir='rtl']
.swagger-ui .endpoint .endpoint-actions li:**first**-child {
  border-right: 0;
}

Will you deal with these kind of internationalization issues in the next release ?
You told me that the direct references will be fixed with the next release, do you know about when it will be ready ?
Either I can use template-url for my internationalization problem and swaggerModules.PARSE for direct references, but I'd prefer not to add too much code, especially if I only change a few lines.
Thanks a lot !

**Comment by mathieuales** [comment]
Hi !
New release published ...
Could you please share your translations when done ?
Thanks !
