### ISSUE TITLE
Href in templates result in CSP warning

### ISSUE THREAD

**Issue by timhoekstra** [Orange-OpenSource/angular-swagger-ui#54]
I'm having trouble with the templates in our application.
Our application has a content security policy(CSP) enabled that does not allow inline javascript.
The templates used in this UI contain elements which have an href to "javascript:;". 
This results in a CSP warning in our application every time we click a link in the swagger UI.

Is it possible to have the library updated with a CSP friendly version which does not contain this behavior?

**Comment by mathieuales** [comment]
Hi !
Ok, i'll include this in next release.
