### ISSUE TITLE
How to render description with Markdown ?

### ISSUE THREAD

**Issue by gitsuraj** [Orange-OpenSource/angular-swagger-ui#57]

**Comment by mathieuales** [comment]
Hi !

Markdown rendering is not natively supported by the component for now, therefore you have to write an `angular-swagger-ui` module to alter display using a thridparty library able to transform markdown into HTML (Ex: https://github.com/chjj/marked), please have a look at https://github.com/Orange-OpenSource/angular-swagger-ui#writing-your-own-modules

I'll try to implement this in next release if you're not in a hury

Regards
