### ISSUE TITLE
XML special characters

### ISSUE THREAD

**Issue by MartinGian** [Orange-OpenSource/angular-swagger-ui#59]
Hi,

If I want to add xml special characters like >, how can I do?

I tried writing & gt; (without the space) in the xml but not works. 

Thanks you! great lib!

**Comment by mathieuales** [comment]
Hi !

I'm not sure to understand where you want this special character to be displayed ...
Can you be more precise and eventually post an example of what you want to do ?

**Comment by MartinGian** [comment]
![image](https://cloud.githubusercontent.com/assets/17177040/20763975/5216c880-b6fa-11e6-8378-815e934c3dfc.png)


That XML comment is showed like:

![image](https://cloud.githubusercontent.com/assets/17177040/20763918/1a315dcc-b6fa-11e6-8581-84568a4aad09.png)

I want to show >, >= instead the encoded characters.

**Comment by mathieuales** [comment]
To help you i need to see the generated JSON or YAML provided to `angular-swagger-ui` and the way you initialize the component
