### ISSUE TITLE
Publish v0.4.0 to npm

### ISSUE THREAD

**Issue by th0r** [Orange-OpenSource/angular-swagger-ui#70]
For some reason the latest version in npm registry is 0.2.7
Could you publish the latest version there?

**Comment by mathieuales** [comment]
Hi !
I didn't published this lib on npm registry, someone else did it.
As it is a client library I don't understand why you need it on npm, you should rather use `bower`

**Comment by th0r** [comment]
> As it is a client library I don't understand why you need it on npm, you should rather use bower

Why I need bower if I already have npm?
If you're talking about bower's version conflicts resolution feature then one can use [`yarn install --flat`](https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-flat) instead.

Also bower seems quite dead: https://github.com/bower/bower/graphs/commit-activity

**Comment by mathieuales** [comment]
done, @see https://www.npmjs.com/package/angular-swagger-ui

**Comment by th0r** [comment]
Thanks a lot!
