### ISSUE TITLE
can't test my APIs

### ISSUE THREAD

**Issue by michel-el-hajj** [Orange-OpenSource/angular-swagger-ui#71]
i integrated the ui into my dashboard and i am getting the yml file from github.
The UI is giving the documentation but i can't add the params to test my API and even the try it out button isn't showing.
Any idea about this problem?
Kindly check the attached picture for a clearer idea. 
<img width="645" alt="screen shot 2017-01-15 at 10 05 40 pm" src="https://cloud.githubusercontent.com/assets/11245140/21965801/cf30c2b4-db6f-11e6-8598-015092db8b0e.png">

**Comment by mathieuales** [comment]
Please have a look at the readme: https://github.com/Orange-OpenSource/angular-swagger-ui#api-explorer

**Comment by michel-el-hajj** [comment]
okay thanks it worked
