### ISSUE TITLE
how to expose Try it out!! functionality?1

### ISSUE THREAD

**Issue by michel-el-hajj** [Orange-OpenSource/angular-swagger-ui#72]
I integrated Swagger Ui in my app and i need to expose the functionality of "Try it out" button. I need to use it in two different ways: 
1- the functionality the way you did which is working fine.
2- the second way is to make it call an API that i made that will return : result : true and data: true in some conditions. 
you use to have a support for this code:
transform try it request
```
$scope.myTransform = function(request){
    request.headers['api_key'] = 's5hredf5hy41er8yhee58';
};
```
Is there a way to do it in this version? like i can do with the input type (json string, yaml string or a url etc.)

**Comment by mathieuales** [comment]
There is no way to override "try it out" functionnality, therefore your 2nd case is not possible

**Comment by michel-el-hajj** [comment]
okay thanks

**Comment by mathieuales** [comment]
You can maybe try this way:

```
angular
    .module('youtApp', ['swaggerUi'])
    .service('yourModule', function($q) {
        this.execute = function(request) {
            var deferred = $q.defer();
            // modify request
            deferred.resolve(true);
            return deferred.promise;
        }

    })
    .run(function(swaggerModules, yourModule){
        swaggerModules.add(swaggerModules.BEFORE_EXPLORER_LOAD, yourModule);
    })
    ...
```
