### ISSUE TITLE
error $injector:unpr when adding swagger-auth.min.js

### ISSUE THREAD

**Issue by michel-el-hajj** [Orange-OpenSource/angular-swagger-ui#73]
Angular Swagger UI is working properly, when i added swagger-auth.min.js in my scripts and added it to my module, i am getting this error:

> Error: [$injector:unpr] http://errors.angularjs.org/1.4.10/$injector/unpr?p0=%24positionProvider%20…DropdownController%20%3C-%20DropdownController%20%3C-%20DropdownController

The funny part is that the swagger auth works fine but my page isn't loading correctly, it's like i have a conflict somewhere.
In my scripts i use ui-bootstrap-tpls-0.13.4.min.js, angular.min.js, bootstrap.min.js etc...

**Comment by mathieuales** [comment]
My mistake: `swagger-auth` module embeds `ui-bootstrap-modal`, I have to rebuild the module without `ui-bootstrap-modal`.

If you need a quick fix, you have 2 solutions:

1. Do not load `ui-bootstrap-tpls-0.13.4.min.js`, use `bower` or `node` to get `ui-bootstrap` sources to only load components you need and which are not already loaded by `swagger-auth`

2. Get `angular-swagger-ui` sources using `bower` or `node` to avoid `ui-bootstrap-modal` being embedded by `swagger-auth`

Version `0.13.4` is quite old, you'd better use `2.4.0` which is the latest compatible version with angular `1.4.x` https://angular-ui.github.io/bootstrap/

**Comment by michel-el-hajj** [comment]
thanks for your time, can you ping me here when you fix the bug?
Thanks in advance
