### ISSUE TITLE
Label of "Open/Hide" link button must be changed to "Show/Hide" 

### ISSUE THREAD

**Issue by amistry79** [Orange-OpenSource/angular-swagger-ui#74]
Label of "Open/Hide" link button must be changed to "Show/Hide" 

Current Behavior: Angular swagger ui is displaying "Open/Hide" link button for each model.
Expected Behavior : Original swagger.io (http://petstore.swagger.io/#/store) ui is displaying "Show/Hide" link button for each model so angular swagger ui must display "Show/Hide" button.

**Comment by mathieuales** [comment]
Hi !
Yes i know but this is my choice: as the opposite of "open" is "close" and not "hide" i decided to choose between "open/close" and "show/hide" ...
This component does at aim at being an exact clone of swagger-ui
Regards

**Comment by amistry79** [comment]
I would still prefer the Open/Close instead of "Open/Hide". This gives the different meaning to the user as per the UX guideline.
