### ISSUE TITLE
Use angular-bootstrap instead of angular-ui-bootstrap

### ISSUE THREAD

**Issue by glenwinters** [Orange-OpenSource/angular-swagger-ui#75]
I'm using [main-bower-files](https://github.com/ck86/main-bower-files) during my build process to get the files specified by the "main" property of `bower.json` for every bower dependency. For `angular-ui-bootstrap`, which `angular-swagger-ui` requires, it's getting `bower_components/angular-ui-bootstrap/index.js` which is not a correct client-side JS file, and it's causing a crash in my build. I noticed that `angular-ui-bootstrap` doesn't even have a `bower.json` file.

The README for `angular-ui-bootstrap` specifies [here](https://github.com/angular-ui/bootstrap#bootstrap-requirements) that you should install `angular-bootstrap`, not `angular-ui-bootstrap` via bower. `angular-bootstrap` does have a `bower.json` file with the "main" property pointing to a usable client-side JS file.

Is there a reason `angular-swagger-ui` is requiring `angular-ui-bootstrap` instead of `angular-bootstrap`?

Thanks!

**Comment by mathieuales** [comment]
Hi !
I'm using `angular-ui-bootstrap` instead of `angular-bootstrap` because you can choose which components you use. This module is only required if you use module `swagger-authentication`
This module should maybe only be used in `dev` mode, I'll put it in devDependencies.
Regards

**Comment by glenwinters** [comment]
Since the authentication module is not included by default, I agree that `angular-ui-bootstrap` shouldn't be in the main dependencies. Thanks for the response.

In the meantime, I was able to get around this problem by ignoring the dependency via `.bowerrc`:
`ignoredDependencies: ["angular-ui-bootstrap"]`
