### ISSUE TITLE
UI Not representing JaxRS @Path when it includes regex

### ISSUE THREAD

**Issue by peterberkman** [Orange-OpenSource/angular-swagger-ui#76]
This is one example and the UI simply display {id} without the preceeding slash and the "Try It!" button fails regardless of what is entered in the "optional" path parameter:

<pre>
@Path("/set/{id : (/id)?}")
</pre>

in the UI:

<pre>
/xxxx/set/{id}
</pre>

and when the "Try It!" button is pressed:

<pre>
Response headers
{
  "date": "Sat, 27 May 2017 03:42:47 GMT",
  "cache-control": "no-cache",
  "server": "Jetty(9.3.14.v20161028)",
  "content-length": "0",
  "allow": "DELETE,POST,GET,PUT,OPTIONS,HEAD"
}
</pre>

**Comment by mathieuales** [comment]
Hi !
You're right, i'll have a look at it asap !

**Comment by mathieuales** [comment]
i'm finally not sure the issue is coming from `angular-swagger-ui`, could you please send the generated swagger.json ?

**Comment by peterberkman** [comment]
unfortunately, it might take me a bit.  I've redone my paths so they work (just added new methods).  I'll try and put one back and generate.

**Comment by peterberkman** [comment]
Mathieuales,
sorry this took so long!  I added the following:

<pre>
@Path("/definitionstest{structure : (/structure)?}")
</pre>

with this result (also in attached zip):

<pre>
"/codeset/definitionstest{structure}": {
"get": {
"tags": [
"Codeset Manager"
],
"summary": "Retrieve the response structure definition(s) supplied to/from Codeset Manager",
"description": "",
"operationId": "getDefinitionsTest_1",
"produces": [
"application/json"
],
"parameters": [
{
"name": "structure",
"in": "path",
"description": "The structure name ('All'=all structures)",
"required": true,
"type": "string",
"pattern": "(/structure)?",
"enum": [
"All",
"AssigningAuthority",
"CodeSet",
"Code"
]
}
],
"responses": {
"200": {
"description": "The operation was successful",
"schema": {
"type": "array",
"items": {
"$ref": "#/definitions/FieldDefinitionType"
}
},
"headers": {
"X-Count": {
"type": "integer",
"format": "int32",
"description": "The total entries in list"
}
}
},
"404": {
"description": "Invalid structure name supplied"
}
},
"security": [
{
"ngsAuthProvider": [
"any"
]
}
]
}
},
</pre>
[swagger-regex-test.zip](https://github.com/Orange-OpenSource/angular-swagger-ui/files/1079660/swagger-regex-test.zip)
