### ISSUE TITLE
Unable to "Try it out" and click to set parameter as body

### ISSUE THREAD

**Issue by konczak** [Orange-OpenSource/angular-swagger-ui#8]
Hi, I have faced strange behaviour while integrating angular-swagger-ui into my project.
Button "Try it out" is missing - neither for my API and http://petstore.swagger.io/v2/swagger.json.
Also field input for body or parameter is missing.

It fails on both Firefox and Chrome.

In browser console I can see for both cases correctly swagger object. Also there is a lot of print for schema.type like "array" and "undefined". As last is printed resources as Array of objects.

I'm using WebJars packages:
angular-swagger-ui 0.1.3

Could you help me with that?

**Comment by mathieuales** [comment]
Hi !

If you are using 0.1.3, you have to add attribute try-it="true" to your directive in order to activate "try it out"
Please have a look at dist/index.html as an example.

Regards

**Comment by konczak** [comment]
You are completely right - I missed it in the example.
It would be good to see that in the README so I keep it open for now.

**Comment by mathieuales** [comment]
You can see it there : https://github.com/Orange-OpenSource/angular-swagger-ui#customization
Take care, parameters names have changed in latest version.
