### ISSUE TITLE
Html5 UI-router compatibiltiy

### ISSUE THREAD

**Issue by matthieut59** [Orange-OpenSource/angular-swagger-ui#81]
Hello,

Any chance to have the permalink=true feature working without the "#" added in the URL.
Indeed due to this # we can t load a new state witu UI-ROUTER as " #" is not allowed in the url.

Any workaround ?

Thks,

matt

**Comment by mathieuales** [comment]
Hi !

I don't think hashbang is incompatible with `ui-router` when using html5 routing: `$locationProvider.html5Mode(true);`

There is no workaround at this time.

Regards
