### ISSUE TITLE
Unable to npm install angular-swagger-ui@0.4.4

### ISSUE THREAD

**Issue by ben-yocum** [Orange-OpenSource/angular-swagger-ui#84]
When trying to install angular-swagger-ui@0.4.4 I get the following error:

```
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "--save" "angular-swagger-ui@0.4.4"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/bootstrap-less-only
npm ERR! 404
npm ERR! 404  'bootstrap-less-only' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'angular-swagger-ui'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\i58558\temp\npm-debug.log
```

To reproduce:

1. Make a new npm project with `npm init` (everything set to default)
2. Try to run `npm install --save angular-swagger-ui@0.4.4`

---

My speculation on the cause of the issue:

On github, `angular-swagger-ui@0.5.1` released this morning. On npm, `angular-swagger-ui@0.4.4` released at about the same time, and `0.5.1` was never released at all. I believe that the wrong version of `angular-swagger-ui` was released onto npm.

[npm-debug.log](https://github.com/Orange-OpenSource/angular-swagger-ui/files/1447387/npm-debug.log)

**Comment by mathieuales** [comment]
why don't you use latest version ? => 0.5.2

**Comment by ben-yocum** [comment]
We've switched to `"angular-swagger-ui": "^0.5.0"`. It's working great.

**Comment by mathieuales** [comment]
great, but 0.5.0 has an issue with 'try it out', you should upgrade to 0.5.2
