### ISSUE TITLE
Issue with rendering multiple api key in angular-swagger-ui

### ISSUE THREAD

**Issue by nijinillath** [Orange-OpenSource/angular-swagger-ui#86]
Hi Team, 
I have more than one api key in my request and they are added in the security element in swagger. While rendering it in angular swagger UI the api authorization are getting clubbed together and the values are not getting assigned properly(only taking the last value provided for all the api key) , also the window is getting closed every time the authorize button is pressed and have to click each time to input api key value.
Is there a better way to render multiple api key ?
Attaching my sample swagger json thanks in advance !! 
[multipleAPIKeySwagger.txt](https://github.com/Orange-OpenSource/angular-swagger-ui/files/1571747/multipleAPIKeySwagger.txt)

**Comment by mathieuales** [comment]
Hi !
At this time there is no way to render multiple API keys.
What you can do is writing a module to manually add headers to requests done by API explorer: https://github.com/Orange-OpenSource/angular-swagger-ui#writing-your-own-modules
Have a look at `BEFORE_EXPLORER_LOAD`
I'll fix this asap

Regards

**Comment by nijinillath** [comment]
Thanks Mathieuales ,  will check on the custom module.
Do let us know once the fix is also available.

Regards !!

**Comment by mathieuales** [comment]
Fixed in version 0.5.5
