### ISSUE TITLE
Syntax Error cant show petstore example

### ISSUE THREAD

**Issue by Vario** [Orange-OpenSource/angular-swagger-ui#88]
I cannot preview any swagger definition file. I tried the mentioned petstore example but I get this error .
<img width="1619" alt="screen shot 2018-01-06 at 18 10 45" src="https://user-images.githubusercontent.com/7426885/34642023-1a344a5a-f30d-11e7-8f67-9f285721ce7c.png">

I use this code to show the swagger-ui

`<div swagger-ui url="https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore.json" api-explorer="true"></div>`

**Comment by mathieuales** [comment]
Hi !
Your URL doesn't point to a JSON file but to an HTML page (try view source in your browser), therefore it cannot be rendered.
Regards

**Comment by Vario** [comment]
Sorry that screenshot was my fault, it is the same result if you add this link, where the petstore json is behind https://www.dropbox.com/s/xsztqtnq6rvzqfm/swagger-definition.json?dl=0
Are there any missing properties i have to define?

**Comment by mathieuales** [comment]
Same issue, this is not a JSON file but an HTML one.
Try with http://petstore.swagger.io/v2/swagger.json

**Comment by Vario** [comment]
I'm afraid, its the same issue here. the dropbox link is a link to a json file, so it should be possible to view this swagger definition.

<img width="1554" alt="screen shot 2018-01-09 at 07 05 37" src="https://user-images.githubusercontent.com/7426885/34707070-ab003b48-f50b-11e7-852c-3a06f2a7da63.png">

**Comment by mathieuales** [comment]
Which version are you using ?
Everything is working here : http://orange-opensource.github.io/angular-swagger-ui/

**Comment by Vario** [comment]
I use the same version :-/
![image](https://user-images.githubusercontent.com/7426885/34724932-be616c7c-f54f-11e7-8995-966e29a4325b.png)

**Comment by mathieuales** [comment]
`url ` param must be a scope variable or a string
if it's a string it must be quoted: `<div swagger-ui url="'http://petstore.swagger.io/v2/swagger.json'" api-explorer="true"></div>`

**Comment by Vario** [comment]
okay thank you, that solved the problem.

**Comment by Vario** [comment]
Sorry for asking again, but could you please extend the documentation to mention the ' ' part for the url.
As well as how to refer to a scope variable?
Adding following code:
`<div swagger-ui url="{{apifileurl}}" api-explorer="true" ng-show="apifileurl"></div>`
gives the output:
![image](https://user-images.githubusercontent.com/7426885/34863692-0d3afba6-f771-11e7-896f-454e3f375791.png)

and using the ' ' around the path 
`<div swagger-ui url="'{{apifileurl}}'" api-explorer="true" ng-show="apifileurl"></div>`
results in 
![image](https://user-images.githubusercontent.com/7426885/34863756-5e48366c-f771-11e7-9153-9d83682553f6.png)

do i have to use ng-src directive or any other?
thank you in advance
