### ISSUE TITLE
There should be callback when "explore" is finished

### ISSUE THREAD

**Issue by konczak** [Orange-OpenSource/angular-swagger-ui#9]
Hi,
I am using multiple groups of API on server side.
On UI I've prepared buttons to switch between them easily.
I would like to display rotating spinner during reload process - that's easy - and hide it when explore completed refresh.
It would be nice to have attribute where I could specify custom callback function which would be called from directive when reload is completed.

Best regards

**Comment by mathieuales** [comment]
Hi !

I had the same idea, will be done in next release.

Regards

**Comment by mathieuales** [comment]
done in 0.2
