### ISSUE TITLE
doesn't it support external references?

### ISSUE THREAD

**Issue by panlina** [Orange-OpenSource/angular-swagger-ui#90]
like:
`
"parameters": [
    {
        "$ref": "./parameters.json#/id"
    }
]
`

**Comment by mathieuales** [comment]
Hi !
Yes it supports external references but it has some limitations :(
`./parameters.json#/id` is not supported for now, please try using `parameters.json#/id` if possible
I'll try to fix it if you reallly need it
Regards

**Comment by panlina** [comment]
`parameters.json#/id` won't work either. Seems the [`resolveReference`](https://github.com/Orange-OpenSource/angular-swagger-ui/blob/f81f0def98c3fe4dae19f37b0b43b2650a84f1b9/src/scripts/services/swagger-model.js#L23) function does not support external references for now. It only supports references in current document.
I am moving the parameter definition into current document and using `#/parameters/id` for now. Glad if you can fix it. Thanks!

**Comment by mathieuales** [comment]
By default external referecences are not enabled, please have a look at documentation: [enable external referecences](https://github.com/Orange-OpenSource/angular-swagger-ui#enable-openapi-external-references)

**Comment by panlina** [comment]
Oh I missed it. Thanks. :)
