### ISSUE TITLE
always the same model and sample when operationId is not specified

### ISSUE THREAD

**Issue by panlina** [Orange-OpenSource/angular-swagger-ui#92]
I do not have `operationId` in every [`OperationObject`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operationObject) since it's not required. When I expand an operation after another, the model and sample value displayed are of the previous operation. This happens for all of the operations I expanded later. All of them display the same model and sample value.
I find it's because it uses `operationId` in the key of model and sample collection:
https://github.com/Orange-OpenSource/angular-swagger-ui/blob/f81f0def98c3fe4dae19f37b0b43b2650a84f1b9/src/scripts/controllers/swagger-ui-controller.js#L229
https://github.com/Orange-OpenSource/angular-swagger-ui/blob/f81f0def98c3fe4dae19f37b0b43b2650a84f1b9/src/scripts/controllers/swagger-ui-controller.js#L238
So when `operationId` is not specified, `id` will start with `"undefined"`, all operations in the same section will share the same key, and no new model and sample value will be generated.

**Comment by panlina** [comment]
Maybe we can concatenate method and path as a key when `operationId` is not defined? And why `section` is necessary?

**Comment by mathieuales** [comment]
Sorry but it seems required: see [openapi 2.0 spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object)

**Comment by mathieuales** [comment]
All generators i've tested generate an operationId for all operations. As described in [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#fixed-fields-8) lots of tools use this attribute as unique identifier for operations so i think it is highly recommended to define one.
I take your point into account and will think about a fix in further version.
Regards

**Comment by panlina** [comment]
Do you mean those tools that generates the spec from java source code with annotations? It's true that people don't have to worry about `operationId` in this case, but for those who author a spec separately, the `operationId` is somewhat redundant because most operations in a restful service are already well identified by its method, url and parameters thus no need to give it another camelCased name. So I think it's pleasant to allow people omit this property.
Thank you for taking this into account.
