### ISSUE TITLE
 Unknown provider: $swaggerTranslatorProvider

### ISSUE THREAD

**Issue by DileepDivakaran** [Orange-OpenSource/angular-swagger-ui#96]
Hi,
I am new to Angular and GitHub also. So pardon, if this is not the correct forum. I was using the angular-swagger-ui to replicate swagger editor  and in index.html(src/index.html) I have placed the snippet given in view-source:http://orange-opensource.github.io/angular-swagger-ui/#!#addPet. If this is the correct fourm can you help out.

 <script src="assets/angular.js"></script>
        <script src="assets/angular-sanitize.min.js"></script>
        <script src="assets/swagger-ui-min.js"></script> 
        <script src="assets/js-yaml/dist/js-yaml.min.js"></script>
        <script src="assets/marked/marked.min.js"></script>
        <script src="assets/angular-swagger-ui/dist/scripts/modules/swagger-external-references.min.js"></script>
        <script src="assets/angular-swagger-ui/dist/scripts/modules/openapi3-converter.min.js"></script>
        <script src="assets/angular-swagger-ui/dist/scripts/modules/swagger1-converter.min.js"></script>
        <script src="assets/angular-swagger-ui/dist/scripts/modules/swagger-xml-formatter.min.js"></script>
        <script src="assets/angular-swagger-ui/dist/scripts/modules/swagger-yaml-parser.min.js"></script>
        <script src="assets/angular-swagger-ui/dist/scripts/modules/swagger-markdown.min.js"></script>
        <script src="assets/angular-swagger-ui/dist/scripts/modules/swagger-auth-ui-bootstrap-modal.min.js"></script>
    <script type="text/javascript">

But getting error angular.js:138 Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:unpr] Unknown provider: $swaggerTranslatorProvider

https://errors.angularjs.org/1.7.8/$injector/modulerr?p0=myApp&p1=Error%3A%20%5B%24injector%3Aunpr%5D%20Unknown%20provider%3A%20%24swaggerTranslatorProvider%0Ahttps%3A%2F%2Ferrors.angularjs.org%2F1.7.8%2F%24injector%2Funpr%3Fp0%3D%2524swaggerTranslatorProvider%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A4200%2Fassets%2Fangular.js%3A138%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A4200%2Fassets%2Fangular.js%3A4924%3A19%0A%20%20%20%20at%20getService%20(http%3A%2F%2Flocalhost%3A4200%2Fassets%2Fangular.js%3A5084%3A32)%0A%20%20%20%20at%20injectionArgs%20(http%3A%2F%2Flocalhost%3A4200%2Fassets%2Fangular.js%3A5109%3A58)%0A%20%20%20%20at%20Object.invoke%20(http%3A%2F%2Flocalhost%3A4200%2Fassets%2Fangular.js%3A5133%3A18)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2Flocalhost%3A4200%2Fassets%2Fangular.js%3A5030%3A35)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A4200%2Fassets%2Fangular.js%3A5040%3A11%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A4200%2Fassets%2Fangular.js%3A387%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A4200%2Fassets%2Fangular.js%3A5020%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A4200%2Fassets%2Fangular.js%3A4937%3A19)
    at angular.js:138
    at angular.js:5060
    at forEach (angular.js:387)
    at loadModules (angular.js:5020)
    at createInjector (angular.js:4937)
    at doBootstrap (angular.js:1960)
    at bootstrap (angular.js:1981)
    at angularInit (angular.js:1866)
    at angular.js:36430
    at HTMLDocument.trigger (angular.js:3520)

**Comment by mathieuales** [comment]
Hi!
Are you sure this path is correct ?
`<script src="assets/swagger-ui-min.js"></script>`
Try
`<script src="assets/angular-swagger-ui/dist/scripts/swagger-ui-min.js"></script>`
