### ISSUE TITLE
swagger ui fails to show sample response with items in response

### ISSUE THREAD

**Issue by RaghebAD** [Orange-OpenSource/angular-swagger-ui#97]
```
    "responses": {
          "200": {
            "description": "getSummaryFromDateRange response",
            "schema": {
              "items": {
                "$ref": "#/definitions/SummaryResponse"
              }
            }
          }
        }
```
shows yellow line instead of a sample response 

<img width="814" alt="Screen Shot 2019-10-23 at 12 56 58 AM" src="https://user-images.githubusercontent.com/11147590/67337620-10c39800-f530-11e9-8fae-948ebcbb6f9f.png">

I tried the same swagger file on https://editor.swagger.io/ , it works fine.

<img width="796" alt="Screen Shot 2019-10-23 at 12 57 43 AM" src="https://user-images.githubusercontent.com/11147590/67337711-39e42880-f530-11e9-8d8e-57ab37749085.png">

**Comment by mathieuales** [comment]
your api descriptor is missing field `type` which is required as described in openapi spec
